import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import HeroSection from '../components/heroSection'
import Sponsor from '../components/Sponsor'
import Categories from '../components/Categories'
import Profile from '../components/CreateProfile'
import Finder from '../components/find'
import Newsletter from '../components/newsletter'
import Footer from '../components/footer'
export default function Home() {
  return (
    <> 
      <Head>
        <title>Job Search</title>  
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
     <Navbar/>
     <HeroSection/>
     <Sponsor/>
     <Categories/>
     <Profile/>
     <Finder/>
     <Newsletter/>
     <Footer/>
     </>
  )
}
